name: GitHub Readme Stats

on:
  schedule:
    - cron: '0 0 * * *' # S'exécute chaque jour à minuit
  workflow_dispatch: # Permet de le lancer manuellement

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Stats
        uses: stats-organization/github-readme-stats-action@v1
        with:
          gh_token: ${{ secrets.MY_GH_TOKEN }}
          output_dir: stats-cards 
